In [1]:
import pandas as pd
import sklearn
import numpy as np
import pickle
import re

Load paper-text:

In [2]:
%%time
dataset_path = "../resources/interesting_arxiv_papers_textclean.pkl"
df_text = pd.read_pickle(dataset_path)
df_text

Wall time: 223 ms


paper_id                                               text
0       100036  paper present multimod biometr system fingerpr...
1       100075  random trial known ab test select polici contr...
2       100147  deep qnetwork returnbas reinforc learn promis ...
3       100161  studi problem learn polici demonstr combinator...
4       100208  present novel method compress deep convolut ne...
...        ...                                                ...
21797    99842  case combin classifi show product rule aris ma...
21798    99920  propos novel dialogu model framework use binar...
21799    99922  studi classif problem featur acquir cost goal ...
21800    99932  challeng imag process task describ illpos line...
21801    99988  model physic system learn molecular fingerprin...

[21802 rows x 2 columns]

In [3]:
# apply more text_cleaning
def initial_text_cleaning(text):
    #text = text.lower()                                             # transform to lowercase
    #text = re.sub(r'\n', '', text)                                  # remove \n
    #text = re.sub(r'(\(|\[|\{)[^(\)|\]|\})]*(\)|\]|\})', '', text)  # remove everything in parentheses
    #text = re.sub(r'http(s)?:\/\/\S+', '', text)                    # remove url
    #text = re.sub(r'[^a-z\s]', '', text)  #[^\w\s]                  # remove everything that is not a word (therefore also numbers and punctuation)
    text = re.sub(r'\b\w{1,2}\b', '', text)                         # remove all single and double letters
    text = re.sub(r'\b(h|i|j|k|x|y)+\b', '', text)                  # remove some common letters used in formules 
    text = re.sub(r'\s{2,}', ' ', text).strip()                     # reformat spaces
    return text

# text - cleaning:
df_text['text'] = df_text['text'].apply(initial_text_cleaning)

Feature Extraction:

In [4]:
#%%time
#from sklearn.feature_extraction.text import TfidfVectorizer
#
#corpus = df['text']
#tfidf_vect = TfidfVectorizer(max_features=40000, min_df=3, norm='l2', ngram_range=(1, 2))
#features = tfidf_vect.fit_transform(corpus).toarray()
#print(len(tfidf_vect.vocabulary_), features.shape)

In [5]:
## save vectorizer:
#vectorizer_path = "../resources/tdidf_bigram_interesting_vectorizer.pkl"
#with open(vectorizer_path, 'wb') as picklefile:
#    pickle.dump(tfidf_vect, picklefile)

In [6]:
# open vectorizer:
tfidf_vect = None
vectorizer_path = "../resources/tdidf_bigram_interesting_vectorizer.pkl"
with open(vectorizer_path, 'rb') as picklefile:
    tfidf_vect = pickle.load(picklefile)

Split in train and test set:

In [7]:
dataset_path = "../resources/papers-subjects-dataset.pkl"
df = pd.read_pickle(dataset_path)
ids = list(df_text.paper_id)
df = df.loc[df.paper_id.isin(ids)]
df.reset_index(drop=True, inplace=True)
df = df.merge(df_text, how='left', on="paper_id")
df = df.drop(columns='primary-subject', axis=1)
df

paper_id  astro-ph  astro-ph.CO  astro-ph.EP  astro-ph.GA  astro-ph.HE  \
0        41513         0            0            0            0            0   
1        61821         0            0            0            0            0   
2        61822         0            0            0            0            0   
3        61823         0            0            0            0            0   
4        61824         0            0            0            0            0   
...        ...       ...          ...          ...          ...          ...   
21797   101218         0            0            0            0            0   
21798   101219         0            0            0            0            0   
21799   101220         0            0            0            0            0   
21800   101222         0            0            0            0            0   
21801   101223         0            0            0            0            0   

       astro-ph.IM  astro-ph.SR  cond-mat  cond-mat.dis-nn  ...  q-fin.RM  \
0                0            0         0                0  ...         0   
1                0            0         0                0  ...         0   
2                0            0         0                0  ...         0   
3                0            0         0                0  ...         0   
4                0            0         0                0  ...         0   
...            ...          ...       ...              ...  ...       ...   
21797            0            0         0                0  ...         0   
21798            0            0         0                0  ...         0   
21799            0            0         0                0  ...         0   
21800            0            0         0                0  ...         0   
21801            0            0         0                0  ...         0   

       q-fin.ST  q-fin.TR  quant-ph  stat.AP  stat.CO  stat.ME  stat.ML  \
0             0         0         0        0        0        0        0   
1             0         0         0        0        0        0        1   
2             0         0         0        0        0        0        1   
3             0         0         0        0        0        0        0   
4             0         0         0        0        0        0        0   
...         ...       ...       ...      ...      ...      ...      ...   
21797         0         0         0        0        0        0        1   
21798         0         0         0        0        0        0        1   
21799         0         0         0        0        0        0        1   
21800         0         0         0        0        0        0        1   
21801         0         0         0        0        0        0        1   

       stat.OT                                               text  
0            0  investig experienti learn paradigm acquir inte...  
1            0  work establish empir success framework adapt l...  
2            0  paper present oimplement tsne embed techniqu c...  
3            0  nonneg matrix factor ubiquit tool data analysi...  
4            0  paper describ serial parallel composit model m...  
...        ...                                                ...  
21797        0  stateoftheart perform deep learn algorithm led...  
21798        0  mixup propos dataaugment scheme linearli inter...  
21799        0  linear discrimin analysi wellknown method dime...  
21800        0  research investig techniqu data learn bayesian...  
21801        0  aggreg set demonstr effect approach predict me...  

[21802 rows x 135 columns]

In [8]:
subjects = list(df.columns)[2:-1]
subjects_to_remove = []
for s in subjects:
    count_papers = df[s].sum()
    if count_papers == 0:
        print(s, ':', count_papers)
        subjects_to_remove.append(s)

astro-ph.HE : 0
cond-mat.quant-gas : 0
cond-mat.soft : 0
cond-mat.str-el : 0
math.CT : 0
math.GM : 0
math.GN : 0
math.RT : 0
math.SP : 0
nlin.CG : 0
nlin.PS : 0
nucl-ex : 0


In [9]:
df = df.drop(columns=subjects_to_remove, axis=1)
df.head(2)

paper_id  astro-ph  astro-ph.CO  astro-ph.EP  astro-ph.GA  astro-ph.IM  \
0    41513         0            0            0            0            0   
1    61821         0            0            0            0            0   

   astro-ph.SR  cond-mat  cond-mat.dis-nn  cond-mat.mes-hall  ...  q-fin.RM  \
0            0         0                0                  0  ...         0   
1            0         0                0                  0  ...         0   

   q-fin.ST  q-fin.TR  quant-ph  stat.AP  stat.CO  stat.ME  stat.ML  stat.OT  \
0         0         0         0        0        0        0        0        0   
1         0         0         0        0        0        0        1        0   

                                                text  
0  investig experienti learn paradigm acquir inte...  
1  work establish empir success framework adapt l...  

[2 rows x 123 columns]

In [10]:
X_df = df.loc[:, ['paper_id','text']]
y_df = df.drop(columns=['paper_id','text'], axis=1)

from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit

msss = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.2, train_size=None, random_state=0)
train_index, test_index = next(msss.split(X_df, y_df))
print(len(train_index), len(test_index))

C:\Users\mauro\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass test_size=0.2, train_size=None, random_state=0 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


17442 4360


In [11]:
df_train = df.iloc[train_index]
df_test = df.iloc[test_index]

X_train = tfidf_vect.transform(df.iloc[train_index]['text'])
X_test = tfidf_vect.transform(df_test['text'])
print(X_train.shape, X_test.shape)

(17442, 40000) (4360, 40000)


In [12]:
y_train = y_df.iloc[train_index]
y_test = y_df.iloc[test_index]
print(y_train.shape, y_test.shape)

(17442, 121) (4360, 121)


Classification:

In [13]:
%%time
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

model_modes = ['mnb', 'svc', 'lr']
models = {
    'lr': {'name': 'Logistic Regression ',
           'estimator': LogisticRegression(solver='sag')
    },
    'svc': {'name': 'Linear SVC         ',
           'estimator': LinearSVC()
    },
    'mnb': {'name': 'Multinomial NB     ',
           'estimator': MultinomialNB(fit_prior=True, class_prior=None)
    }
}

for model_mode in model_modes:
    print("="*20, "OneVsRest - %s" % models[model_mode]['name'], "="*20)
    classifier = OneVsRestClassifier(models[model_mode]['estimator'], n_jobs=-1)
    print("... training on %s samples" % X_train.shape[0])
    classifier.fit(X_train, y_train)
    print("... predicting on train set")
    print("\t\t score = %s" % classifier.score(X_train, y_train))
    prediction_train = classifier.predict(X_train)
    print("... predicting on test set")
    print("\t\t score = %s" % classifier.score(X_test, y_test))
    prediction_test = classifier.predict(X_test)
    # compare prediction_train-train ; compare prediction_test-test
    y_ntrain=y_train.to_numpy()
    y_ntest=y_test.to_numpy()
    subjects = list(y_train.columns)
    for i,subject in enumerate(subjects):
        print("\nsubject '%s':" % subject)
        print("- train:")
        print("%s\taccuracy = %s" %(confusion_matrix(y_ntrain[:,i],prediction_train[:,i]), accuracy_score(y_ntrain[:,i],prediction_train[:,i])))
        print("- test:")
        print("%s\taccuracy = %s" %(confusion_matrix(y_ntest[:,i],prediction_test[:,i]), accuracy_score(y_ntest[:,i],prediction_test[:,i])))
    print('\n\n')

==================== OneVsRest - Multinomial NB      ====================
... training on 17442 samples
... predicting on train set
		 score = 0.500515995872033
... predicting on test set
		 score = 0.48509174311926606

subject 'astro-ph':
- train:
[[17439     0]
 [    3     0]]	accuracy = 0.999828001375989
- test:
[[4359    0]
 [   1    0]]	accuracy = 0.9997706422018349

subject 'astro-ph.CO':
- train:
[[17440     0]
 [    2     0]]	accuracy = 0.9998853342506593
- test:
[[4359    0]
 [   1    0]]	accuracy = 0.9997706422018349

subject 'astro-ph.EP':
- train:
[[17440     0]
 [    2     0]]	accuracy = 0.9998853342506593
- test:
[[4359    0]
 [   1    0]]	accuracy = 0.9997706422018349

subject 'astro-ph.GA':
- train:
[[17438     0]
 [    4     0]]	accuracy = 0.9997706685013187
- test:
[[4359    0]
 [   1    0]]	accuracy = 0.9997706422018349

subject 'astro-ph.IM':
- train:
[[17428     0]
 [   14     0]]	accuracy = 0.9991973397546153
- test:
[[4356    0]
 [   4    0]]	accuracy = 0.9990825

### New attempt with a simplified taxonomy:

In [14]:
dataset_path = "../resources/papers-subjects-dataset-56.pkl"
df_56 = pd.read_pickle(dataset_path)
df_56 = df_56.loc[df_56['paper_id'].isin(list(df['paper_id']))]
df_56.reset_index(drop=True, inplace=True)
df_56

paper_id  astro-ph  cond-mat  gr-qc  math-ph  nlin  physics  quant-ph  \
0        41513         0         0      0        0     0        0         0   
1        61821         0         0      0        0     0        0         0   
2        61822         0         0      0        0     0        0         0   
3        61823         0         0      0        0     0        0         0   
4        61824         0         0      0        0     0        0         0   
...        ...       ...       ...    ...      ...   ...      ...       ...   
21797   101218         0         0      0        0     0        0         0   
21798   101219         0         0      0        0     0        0         0   
21799   101220         0         0      0        0     0        0         0   
21800   101222         0         0      0        0     0        0         0   
21801   101223         0         0      0        0     0        0         0   

       math  cs.AI  ...  cs.SC  cs.SY  q-bio  q-fin  stat.ML  stat  eess  \
0         0      1  ...      0      0      0      0        0     0     0   
1         0      1  ...      0      0      0      0        1     0     0   
2         0      0  ...      0      0      0      0        1     0     0   
3         1      0  ...      0      0      0      0        0     0     0   
4         0      0  ...      0      0      0      0        0     0     0   
...     ...    ...  ...    ...    ...    ...    ...      ...   ...   ...   
21797     0      0  ...      0      0      0      0        1     0     0   
21798     0      1  ...      0      0      0      0        1     0     0   
21799     0      0  ...      0      0      0      0        1     0     0   
21800     0      1  ...      0      0      0      0        1     0     0   
21801     0      1  ...      0      0      0      0        1     0     0   

       econ  hep  nucl  
0         0    0     0  
1         0    0     0  
2         0    0     0  
3         0    0     0  
4         0    0     0  
...     ...  ...   ...  
21797     0    0     0  
21798     0    0     0  
21799     0    0     0  
21800     0    0     0  
21801     0    0     0  

[21802 rows x 57 columns]

Split in train and test set:

In [15]:
#df_train = df.iloc[train_index]
#df_test = df.iloc[test_index]
#
#X_train = tfidf_vect.transform(df.iloc[train_index]['text'])
#X_test = tfidf_vect.transform(df_test['text'])
print(X_train.shape, X_test.shape)

(17442, 40000) (4360, 40000)


In [16]:
y_df = df_56.drop(columns=['paper_id'], axis=1)
y_train = y_df.iloc[train_index]
y_test = y_df.iloc[test_index]
print(y_train.shape, y_test.shape)

(17442, 56) (4360, 56)


Classification:

In [17]:
%%time
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

model_modes = ['mnb', 'svc', 'lr']
models = {
    'lr': {'name': 'Logistic Regression ',
           'estimator': LogisticRegression(solver='sag')
    },
    'svc': {'name': 'Linear SVC         ',
           'estimator': LinearSVC()
    },
    'mnb': {'name': 'Multinomial NB     ',
           'estimator': MultinomialNB(fit_prior=True, class_prior=None)
    }
}

for model_mode in model_modes:
    print("="*20, "OneVsRest - %s" % models[model_mode]['name'], "="*20)
    classifier = OneVsRestClassifier(models[model_mode]['estimator'], n_jobs=-1)
    print("... training on %s samples" % X_train.shape[0])
    classifier.fit(X_train, y_train)
    print("... predicting on train set")
    print("\t\t score = %s" % classifier.score(X_train, y_train))
    prediction_train = classifier.predict(X_train)
    print("... predicting on test set")
    print("\t\t score = %s" % classifier.score(X_test, y_test))
    prediction_test = classifier.predict(X_test)
    # compare prediction_train-train ; compare prediction_test-test
    y_ntrain=y_train.to_numpy()
    y_ntest=y_test.to_numpy()
    subjects = list(y_train.columns)
    for i,subject in enumerate(subjects):
        print("\nsubject '%s':" % subject)
        print("- train:")
        print("%s\taccuracy = %s" %(confusion_matrix(y_ntrain[:,i],prediction_train[:,i]), accuracy_score(y_ntrain[:,i],prediction_train[:,i])))
        print("- test:")
        print("%s\taccuracy = %s" %(confusion_matrix(y_ntest[:,i],prediction_test[:,i]), accuracy_score(y_ntest[:,i],prediction_test[:,i])))
    print('\n\n')

==================== OneVsRest - Multinomial NB      ====================
... training on 17442 samples
... predicting on train set
		 score = 0.5015479876160991
... predicting on test set
		 score = 0.4864678899082569

subject 'astro-ph':
- train:
[[17423     0]
 [   19     0]]	accuracy = 0.9989106753812637
- test:
[[4353    0]
 [   7    0]]	accuracy = 0.9983944954128441

subject 'cond-mat':
- train:
[[17403     0]
 [   39     0]]	accuracy = 0.9977640178878568
- test:
[[4351    0]
 [   9    0]]	accuracy = 0.9979357798165137

subject 'gr-qc':
- train:
[[17440     0]
 [    2     0]]	accuracy = 0.9998853342506593
- test:
[[4360]]	accuracy = 1.0

subject 'math-ph':
- train:
[[17439     0]
 [    3     0]]	accuracy = 0.999828001375989
- test:
[[4359    0]
 [   1    0]]	accuracy = 0.9997706422018349

subject 'nlin':
- train:
[[17434     0]
 [    8     0]]	accuracy = 0.9995413370026374
- test:
[[4358    0]
 [   2    0]]	accuracy = 0.9995412844036697

subject 'physics':
- train:
[[17310     0]